<!-- Verificamos si existe la cookie -->
<?php if (isset($_COOKIE['VotaDatAdmin']) && isset($_GET['id'])) : ?>
    <!doctype html>
    <html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>Cambiar contraseña</title>
        <link href="../estilo.css" rel="stylesheet" type="text/css">
    </head>

    <body>
        <form name="cambioclave" action="cambiarclave.php" method="post">
            <h2>CAMBIAR CONTRASEÑA</h2>
            <table cellpadding="0" cellspacing="5" border="0">
                <tr>
                    <td><label for="clave_actual">Clave actual:</label></td>
                    <td><input type="password" name="clave_actual" size="20" maxlength="30" title="Escriba la clave actual." /></td>
                </tr>
                <tr>
                    <td><label for="clave1_nueva">Clave nueva:</label><br>(mánimo 4 caracteres)</td>
                    <td><input type="password" name="clave1_nueva" size="20" maxlength="30" title="Escriba la nueva clave" /></td>
                </tr>
                <tr>
                    <td><label for="clave2_nueva">Confirmar clave nueva:</label></td>
                    <td><input type="password" name="clave2_nueva" size="20" maxlength="30" title="Escriba la confirmación de la nueva clave" /></td>
                </tr>
            </table><br>
            <input type="hidden" name="identificador" value="<?php echo ($_GET['id']); ?>" />
            <div class="cen">
                <input type="submit" name="envia_cambioclave" value="Guardar datos" title="Guardar los datos" />
            </div>
        </form>

    </body>

    </html>
<?php endif; ?>
