<!doctype html>
<html>

<head>
    <title>Actualizacón de datos</title>
    <link href="../estilo.css" rel="stylesheet" type="text/css">
</head>

<body>
    <?php include_once("../java.html"); ?>
    <table>
        <tr class="confirma">
            <td>
                <p class="cen">
                    <strong><img style="float:left" src="../iconos/edit.png" alt="Edit">Los datos fueron actualizados satisfactoriamente.</strong><br><br>
                    <input type=button value="Cerrar" onclick="CerrarVentana()">
                </p>
            </td>
        </tr>
    </table><br>
</body>

</html>
