<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EducoVota - <?php print($institución['nombre'] ?? 'Institución'); ?></title>
    <link href="style-ingresar.css" rel="stylesheet">
</head>
<body>
    <main>
        <section class="form-login">
            <img src="iconos/EscudoColegio.png" alt="Escudo de Colegio">
            <h2>ADMINISTRACIÓN EDUCOVOTA</h2>
            <form id="administracion" action="administrador/index.php" method="post">
                <input type="hidden" name="envia_acceso">
                <input type="text" name="usuario" placeholder="Nombre de usuario" title="Escriba el nombre de usuario" autofocus>
                <input type="password" name="clave" placeholder="Contraseña" title="Escriba la contraseña de acceso">
                <input type="submit" title="Iniciar sesión" value="Iniciar Sesión"></input>
            </form>
        </section>
        <section class="rules">
            <img src="iconos/EscudoColombia.png" alt="Escudo de Colegio">
            <h3>Para realizar el proceso de votación siga los siguientes pasos:</h3>
            <ul>
                <li>
                    <img src="iconos/n1.png" alt="#1">
                    <span>Ingrese al sistema de votación, escribiendo su número de documento (costado derecho de esta página).</span>
                </li>
                <li>
                    <img src="iconos/n2.png" alt="#2">
                    <span>Al ingresar al sistema encontrará el tarjetón electoral para votar por sus representantes preferidos.
                        Seleccione los de su preferencia dando clic sobre la foto.</span>
                </li>
                <li>
                    <img src="iconos/n3.png" alt="#3">
                    <span>Para registrar su voto de clic en el botón <strong>votar</strong>.</span>
                </li>
            </ul>
        </section>
    </main>
    <footer>
        <span>&copy; 2022 <a href="http://localhost:8088">EducoVota</a>. Todos los derechos reservados.</span>
    </footer>

    <script src="index.js"></script>
</body>
</html>
