<?php

require_once("../funciones.php");
require_once("../conexionBD.php");

$db = conectarse();
//****** Verificamos si existe la cookie *****/
if (isset($_COOKIE['ClermontDatAdmin'])) {
    if (isset($_GET['id'])) {
        $resp = $db->query(sprintf("select * from administradores where md5(administradores.id)=%s", comillas($_GET['id'])));
        if ($row = $resp->fetch_array(MYSQLI_ASSOC)) {
            ?>
            <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
            <html>

            <head>
                <title>Colegio Clermont - Perfil de administrador</title>
                <link href="../estilo.css" rel="stylesheet" type="text/css" />
            </head>

            <body>
                <form name="cambioperfil" action="perfil.php" method="post">

                    <h2>MODIFICAR PERFIL</h2>
                    <table cellpadding="0" cellspacing="5" border="0">

                        <tr>
                            <td><label for="admusuario">Usuario:</label></td>
                            <?php
                            //**** Verificar privilegios administrador ******
                            $resp2 = $db->query(sprintf("select acc_pregunta from acceso where acc_id=%d and acc_tipo=%s", $_COOKIE['ClermontDatAdmin'], comillas("ADM")));
                            $row2 = $resp->fetch_array(MYSQLI_ASSOC);
                            if ($row2['acc_pregunta'] == "SUPER") {
                                echo '<td><input type="text" name="admusuario" value="' . $row['usuario'] . '" size="30" maxlength="50" title="Nombre del usuario administrador" /></td>';
                            } else {
                                echo '<td><input type="text" name="admusuario" value="' . $row['usuario'] . '" size="30" maxlength="50" title="Nombre del usuario administrador" disabled="disabled" /></td>';
                            }
                            ?>
                        </tr>

                        <tr>
                            <td><label for="admnombres">Nombres:</label></td>
                            <td><input type="text" name="admnombres" value="<?php echo ($row['adm_nombres']); ?>" size="30" maxlength="50" title="Nombres del administrador" /></td>
                        </tr>

                        <tr>
                            <td><label for="admapellidos">Apellidos:</label></td>
                            <td><input type="text" name="admapellidos" value="<?php echo ($row['adm_apellidos']); ?>" size="30" maxlength="50" title="Apellidos del administrador" /></td>
                        </tr>

                    </table><br>
                    <input type="hidden" name="admidentifica" value="<?php echo ($row['id']); ?>" />
                    <div class="cen">
                        <input type="submit" name="envia_perfil" value="Guardar datos" title="Guardar los datos" />
                    </div>
                </form>

            <?php
        } else {
            echo '<table>';
            echo '<tr><td class="cen" colspan="2"><strong>No hay datos para el administrador</strong></td></tr>';
            echo '</table>';
        }
        echo '</body>';
        echo '</html>';
    }

    $db->close();
}
