<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EducoVota - <?php print($institución['nombre'] ?? 'Nombre de la institución'); ?></title>
</head>
<body>
    <main>
        <section class="form-login">
            <img src="assets/images/escudo-colegio.png" alt="Escudo de Colegio" width="250">
            <h2>
                <span><?php print($institución['nombre']); ?></span>
                <span><?php print($institución['descripcion']); ?></span>
            </h2>
            <form id="consulta" action="index.php" method="post">
                <input type="text" name="documento" placeholder="Documento del estudiante" title="Escriba el documento del estudiante">
                <?php if ($institución['clave'] == "S") : ?>
                    <input type="password" name="contra" placeholder="Contraseña" title="Escriba la contraseña de acceso">
                <?php endif; ?>
                <input type="submit" name="envia_consulta" value="Ingresar" title="Ingresar al sistema">
            </form>
        </section>
        <section class="rules">
            <img src="assets/images/escudo-colombia.png" alt="Escudo de Colegio" width="250">
            <h3>Para realizar el proceso de votación siga los siguientes pasos:</h3>
            <ul>
                <li>
                    <img src="assets/icons/n1.png" alt="#1">
                    <span>Ingrese al sistema de votación, escribiendo su número de documento (costado derecho de esta página).</span>
                </li>
                <li>
                    <img src="assets/icons/n2.png" alt="#2">
                    <span>Al ingresar al sistema encontrará el tarjetón electoral para votar por sus representantes preferidos.
                        Seleccione los de su preferencia dando clic sobre la foto.</span>
                </li>
                <li>
                    <img src="assets/icons/n3.png" alt="#3">
                    <span>Para registrar su voto de clic en el botón <strong>votar</strong>.</span>
                </li>
            </ul>
        </section>
    </main>
    <footer>
        <span>&copy; 2022 <a href="http://localhost:8000">SVE</a>. Todos los derechos reservados.</span>
    </footer>

    <script src="assets/js/bundle.js"></script>
</body>
</html>
